services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.ugi0.org
    ports:
      - "20025:25"
      - "20465:465"
      - "20587:587"
      - "20993:993"
    volumes:
      - ./mailworker/docker-data/dms/mail-data/:/var/mail/
      - ./mailworker/docker-data/dms/mail-state/:/var/mail-state/
      - ./mailworker/docker-data/dms/mail-logs/:/var/log/mail/
      - ./mailworker/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./mailworker/certs:/tmp/docker-mailserver/certs:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
   #   - ./postfix-conf/main.cf:/etc/postfix/main.cf
    env_file: ./mailworker/.env
    cap_add:
      - NET_ADMIN
    restart: on-failure
    networks:
      default:
        aliases:
          - mail.ugi0.org
      mailnet:
        aliases:
          - mail.ugi0.org


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mailserver-frontend
    ports:
      - "20080:3000"
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
    restart: on-failure
  
  database:
    image: postgres:16
    container_name: mailserver-db
    env_file:
      - backend/db.env
    volumes:
      - mailserver-db-data:/var/lib/postgresql/data
      - ./backend/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql:ro
    restart: on-failure

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mailserver-backend
    ports:
      - "20081:8080"
    env_file:
      - backend/.env
    restart: on-failure
    networks:
      - default
      - mailnet


  sieve-helper:
    build:
      context: ./sieve-helper
      dockerfile: Dockerfile
    container_name: mailserver-sieve-helper
    env_file:
      - ./sieve-helper/.env
    restart: on-failure
    networks:
      - default
      - mailnet

networks:
  mailnet:
    external: true

volumes:
  mailserver-db-data:
